language:
  - cpp

install:
  - sudo pip install pytest
  - sudo pip install cffi
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9 g++-4.9

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - py.test -vv test/test.py build

notifications:
  email: false
